Leave `moduleResolution` value unspecified in `tsconfig.json` to fix Jest error `error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.` when running `npm test`. Based on https://github.com/kulshekhar/ts-jest/issues/4198#issuecomment-1863407516.